package com.blog.entity;
// Generated 2017-4-21 20:11:15 by Hibernate Tools 4.0.0.Final

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	private Integer id;
	private String title;
	private String content;
	private String image;
	private String time;
	private String editer;
	private Integer count;
	private Integer count1;
	private String type;
	private String notice;
	private String keywords;

	public Article() {
	}

	public Article(String title, String content, String image, String time, String editer, Integer count,
			Integer count1, String type, String notice, String keywords) {
		this.title = title;
		this.content = content;
		this.image = image;
		this.time = time;
		this.editer = editer;
		this.count = count;
		this.count1 = count1;
		this.type = type;
		this.notice = notice;
		this.keywords = keywords;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getEditer() {
		return this.editer;
	}

	public void setEditer(String editer) {
		this.editer = editer;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getCount1() {
		return this.count1;
	}

	public void setCount1(Integer count1) {
		this.count1 = count1;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

}
