package com.blog.entity;
// Generated 2017-5-4 14:29:03 by Hibernate Tools 4.0.0.Final

/**
 * Base generated by hbm2java
 */
public class Base implements java.io.Serializable {

	private Integer id;
	private String title;
	private String stitle;

	public Base() {
	}

	public Base(String title, String stitle) {
		this.title = title;
		this.stitle = stitle;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getStitle() {
		return this.stitle;
	}

	public void setStitle(String stitle) {
		this.stitle = stitle;
	}

}
