package com.blog.entity;
// Generated 2017-5-18 16:53:21 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Critique generated by hbm2java
 */
public class Critique implements java.io.Serializable {

	private Integer id;
	private Critique critique;
	private User user;
	private Integer articleId;
	private String content;
	private String time;
	private String photo;
	private String type;
	private String notice;
	private Set critiques = new HashSet(0);

	public Critique() {
	}

	public Critique(User user) {
		this.user = user;
	}

	public Critique(Critique critique, User user, Integer articleId, String content, String time, String photo,
			String type, String notice, Set critiques) {
		this.critique = critique;
		this.user = user;
		this.articleId = articleId;
		this.content = content;
		this.time = time;
		this.photo = photo;
		this.type = type;
		this.notice = notice;
		this.critiques = critiques;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Critique getCritique() {
		return this.critique;
	}

	public void setCritique(Critique critique) {
		this.critique = critique;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getArticleId() {
		return this.articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	public Set getCritiques() {
		return this.critiques;
	}

	public void setCritiques(Set critiques) {
		this.critiques = critiques;
	}

}
