package com.blog.entity;
// Generated 2017-4-21 20:11:15 by Hibernate Tools 4.0.0.Final

/**
 * Daily generated by hbm2java
 */
public class Daily implements java.io.Serializable {

	private Integer id;
	private String content;
	private String time;
	private String description;

	public Daily() {
	}

	public Daily(String content, String time) {
		this.content = content;
		this.time = time;
	}

	public Daily(String content, String time, String description) {
		this.content = content;
		this.time = time;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
