package com.blog.entity;
// Generated 2017-4-21 20:11:15 by Hibernate Tools 4.0.0.Final

/**
 * Manager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	private Integer id;
	private String account;
	private String password;
	private String role;
	private String notice;

	public Manager() {
	}

	public Manager(String account, String password, String role, String notice) {
		this.account = account;
		this.password = password;
		this.role = role;
		this.notice = notice;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

}
