package com.blog.entity;
// Generated 2017-5-18 16:53:21 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String account;
	private String password;
	private String headpic;
	private String contact;
	private Date createdate;
	private String other0;
	private String other1;
	private Set critiques = new HashSet(0);

	public User() {
	}

	public User(String name, String account, String password) {
		this.name = name;
		this.account = account;
		this.password = password;
	}

	public User(String name, String account, String password, String headpic, String contact, Date createdate,
			String other0, String other1, Set critiques) {
		this.name = name;
		this.account = account;
		this.password = password;
		this.headpic = headpic;
		this.contact = contact;
		this.createdate = createdate;
		this.other0 = other0;
		this.other1 = other1;
		this.critiques = critiques;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getHeadpic() {
		return this.headpic;
	}

	public void setHeadpic(String headpic) {
		this.headpic = headpic;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getOther0() {
		return this.other0;
	}

	public void setOther0(String other0) {
		this.other0 = other0;
	}

	public String getOther1() {
		return this.other1;
	}

	public void setOther1(String other1) {
		this.other1 = other1;
	}

	public Set getCritiques() {
		return this.critiques;
	}

	public void setCritiques(Set critiques) {
		this.critiques = critiques;
	}

}
